# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: DeployToPROD
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(known_host)
          sshPublicKey: $(public_key)
          sshKeySecureFile: 'ssh_private_key'
        displayName: "Create SSH files"
      - script: |
          ssh -i .ssh/ssh_private_key $(host) 'ls -al'
        displayName: 'Configure production server'


