version: '3'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: examplepwd
      POSTGRES_USER: exampleusr
      POSTGRES_DB: todo
  myappspa:
    build: ./myappspa
    image: ${ACR_URL}/myappspa:1 
    ports: 
      - "8080:80"
    environment: 
      TODOAPIPROTOCOL: "http"
      TODOAPISERVER: "localhost"
      TODOAPIPORT: "8081"
  myapptodo:
    build: ./myapptodo
    image: ${ACR_URL}/myapptodo:1 
    depends_on:
       - db
    ports: 
      - "8081:8080"
    environment: 
      POSTGRESQL_URL: "jdbc:postgresql://db:5432/todo?user=exampleusr&password=examplepwd"
